/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalmatedisc;

import java.awt.Color;
import java.awt.MenuItem;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alfredo
 */
public class Final extends javax.swing.JFrame {

    /**
     * Creates new form Final
     */
    public Final() {
        initComponents();
        MenuItem m;
        mnuProblemas.setMnemonic('P');
        mnuProblema1.setMnemonic('1');
        mnuProblema4.setMnemonic('4');
        mnuSalir.setMnemonic('s');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuProblemas = new javax.swing.JMenu();
        mnuProblema1 = new javax.swing.JMenuItem();
        mnuProblema4 = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matematicas Discretas - Proyecto Final");
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/relaciones.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout pnlFondoLayout = new org.jdesktop.layout.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFondoLayout.createSequentialGroup()
                .add(175, 175, 175)
                .add(lblFondo)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFondoLayout.createSequentialGroup()
                .add(146, 146, 146)
                .add(lblFondo)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        mnuProblemas.setText("Problemas");

        mnuProblema1.setText("Problema 1");
        mnuProblema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProblema1ActionPerformed(evt);
            }
        });
        mnuProblemas.add(mnuProblema1);

        mnuProblema4.setText("Problema 4");
        mnuProblema4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProblema4ActionPerformed(evt);
            }
        });
        mnuProblemas.add(mnuProblema4);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuProblemas.add(mnuSalir);

        mnuPrincipal.add(mnuProblemas);

        setJMenuBar(mnuPrincipal);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(pnlFondo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFondo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuProblema4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProblema4ActionPerformed
        // TODO add your handling code here:
        Problema4 dialog = new Problema4(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_mnuProblema4ActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuProblema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProblema1ActionPerformed
        // TODO add your handling code here:
        Problema1 dialog = new Problema1(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_mnuProblema1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Final().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFondo;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenuItem mnuProblema1;
    private javax.swing.JMenuItem mnuProblema4;
    private javax.swing.JMenu mnuProblemas;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
