/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalmatedisc;

import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author alfredo
 */
public class Problema4 extends javax.swing.JDialog {

    private Color color;
    private int porcentaje = 0;
    private String mensajes;
    DecimalFormat df = new DecimalFormat("0.00");
    private ArrayList<String> relaciones;

    /**
     * Creates new form Problema4
     */
    public Problema4(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        color = txtConjunto.getForeground();
        txtConjunto.setDocument(new LimitadorCaracteres(txtConjunto, 13));
        txtConjunto.setText("1,2,3,4");
        txtConjunto.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblConjunto = new javax.swing.JLabel();
        txtConjunto = new javax.swing.JTextField();
        lblRelaciones = new javax.swing.JLabel();
        txtRelaciones = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaRelacionesTransitivas = new javax.swing.JTextArea();
        lblConjuntosDistintos = new javax.swing.JLabel();
        btnCalcularRelaciones = new javax.swing.JButton();
        pgsProgreso = new javax.swing.JProgressBar();
        lblProductoCartesiano = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaProductoCartesiano = new javax.swing.JTextArea();
        lblTransitivas = new javax.swing.JLabel();
        txtSubconjuntos = new javax.swing.JTextField();
        btnMostrarRelaciones = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblPorcentaje = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Problema 4");

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitulo.setText("PROYECTO FINAL - PROBLEMA 4");

        lblConjunto.setText("Introduce los elementos del conjunto: ");

        txtConjunto.setForeground(new java.awt.Color(204, 204, 255));
        txtConjunto.setText("1,2,3,4,5,6,7");
        txtConjunto.setToolTipText("Separa con comas los elementos del conjunto");
        txtConjunto.setCaretPosition(0);
        txtConjunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConjuntoMouseClicked(evt);
            }
        });
        txtConjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConjuntoActionPerformed(evt);
            }
        });
        txtConjunto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConjuntoFocusLost(evt);
            }
        });
        txtConjunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConjuntoKeyTyped(evt);
            }
        });

        lblRelaciones.setText("Total de relaciones:");

        txtRelaciones.setEnabled(false);

        txtaRelacionesTransitivas.setColumns(20);
        txtaRelacionesTransitivas.setRows(5);
        txtaRelacionesTransitivas.setEnabled(false);
        jScrollPane1.setViewportView(txtaRelacionesTransitivas);

        lblConjuntosDistintos.setText("Relaciones Transtivicas");

        btnCalcularRelaciones.setText("Calcular Relaciones");
        btnCalcularRelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRelacionesActionPerformed(evt);
            }
        });

        lblProductoCartesiano.setText("Producto Cartesiano:");

        txtaProductoCartesiano.setColumns(20);
        txtaProductoCartesiano.setRows(5);
        txtaProductoCartesiano.setEnabled(false);
        jScrollPane2.setViewportView(txtaProductoCartesiano);

        lblTransitivas.setText("Total de Relaciones Transitivas:");

        txtSubconjuntos.setEnabled(false);

        btnMostrarRelaciones.setText("Mostrar Relaciones");
        btnMostrarRelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarRelacionesActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(204, 0, 0));

        lblPorcentaje.setText("0.00 %");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlContenedorLayout = new org.jdesktop.layout.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlContenedorLayout.createSequentialGroup()
                .add(42, 42, 42)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlContenedorLayout.createSequentialGroup()
                        .add(lblConjuntosDistintos)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlContenedorLayout.createSequentialGroup()
                        .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(pnlContenedorLayout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(btnSalir)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(lblPorcentaje))
                            .add(pgsProgreso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jScrollPane1)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, pnlContenedorLayout.createSequentialGroup()
                                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(lblConjunto)
                                    .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(lblProductoCartesiano)
                                        .add(lblRelaciones))
                                    .add(lblTransitivas))
                                .add(37, 37, 37)
                                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(pnlContenedorLayout.createSequentialGroup()
                                        .add(txtConjunto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(btnCalcularRelaciones))
                                    .add(jScrollPane2)
                                    .add(pnlContenedorLayout.createSequentialGroup()
                                        .add(txtRelaciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(pnlContenedorLayout.createSequentialGroup()
                                        .add(txtSubconjuntos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 198, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(btnMostrarRelaciones))))
                            .add(pnlContenedorLayout.createSequentialGroup()
                                .add(lblTitulo)
                                .add(172, 172, 172)))
                        .add(88, 88, 88))))
            .add(pnlContenedorLayout.createSequentialGroup()
                .add(58, 58, 58)
                .add(lblError)
                .add(0, 0, Short.MAX_VALUE))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlContenedorLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(lblTitulo)
                .add(12, 12, 12)
                .add(lblError)
                .add(18, 18, 18)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblConjunto)
                    .add(txtConjunto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnCalcularRelaciones))
                .add(18, 18, 18)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblRelaciones)
                    .add(txtRelaciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblProductoCartesiano)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTransitivas)
                    .add(txtSubconjuntos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnMostrarRelaciones))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lblConjuntosDistintos)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pgsProgreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblPorcentaje)
                    .add(btnSalir))
                .add(19, 19, 19))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(81, 81, 81)
                .add(pnlContenedor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 773, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlContenedor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConjuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConjuntoMouseClicked
        // TODO add your handling code here:
        if (txtConjunto.getForeground() == color) {
            txtConjunto.setText("");
            txtConjunto.setForeground(txtRelaciones.getForeground());
        }
    }//GEN-LAST:event_txtConjuntoMouseClicked

    private void txtConjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConjuntoActionPerformed
        // TODO add your handling code here:
        btnCalcularRelacionesActionPerformed(evt);
    }//GEN-LAST:event_txtConjuntoActionPerformed

    private void txtConjuntoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConjuntoFocusLost
        // TODO add your handling code here:
        if (txtConjunto.getText().equalsIgnoreCase("")) {
            txtConjunto.setForeground(color);
            txtConjunto.setText("1,2,3,4,5,6,7");
            txtRelaciones.setText("");
            txtaProductoCartesiano.setText("");
            txtSubconjuntos.setText("");
            txtaRelacionesTransitivas.setText("");
            lblError.setText("");
            pgsProgreso.setValue(0);
        }
    }//GEN-LAST:event_txtConjuntoFocusLost

    private void txtConjuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConjuntoKeyTyped
        // TODO add your handling code here:
        if (txtConjunto.getForeground() == color) {
            txtConjunto.setText("");
            txtConjunto.setForeground(txtRelaciones.getForeground());
        }
    }//GEN-LAST:event_txtConjuntoKeyTyped

    private void btnCalcularRelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRelacionesActionPerformed
        // TODO add your handling code here:
        if (!validador() || !esValidaN(txtConjunto.getText())) {
            return;
        }
        mensajes = "";
        lblError.setText(mensajes);
        String pares;
        int totalTransitivas;
        int totalRelaciones;
        porcentaje = 0;

        txtaRelacionesTransitivas.setText("");
        lblPorcentaje.setText("0.00 %");
        pgsProgreso.setValue(0);
        pares = generarProductoCartesiano(txtConjunto.getText().split(","));
        totalRelaciones = (int) Math.pow(2, txtConjunto.getText().split(",").length);
        relaciones = obtenerTransitivas(pares.split(", "));
        totalTransitivas = relaciones.size();
        pgsProgreso.setMaximum(totalTransitivas);
        txtRelaciones.setText("" + totalRelaciones);
        txtaProductoCartesiano.setText(pares);
        txtSubconjuntos.setText("" + pgsProgreso.getMaximum());
    }//GEN-LAST:event_btnCalcularRelacionesActionPerformed

    private boolean esValidaN(String conjunto) {
        boolean valida = true;
        String elementos[] = conjunto.split(",");
        for (String elemento : elementos) {
            if (!elemento.matches("[1-7]")) {
                valida = false;
                mensajes = "Debe ingresar un conjunto de elementos n menor a o igual a 7.\n "
                        + "Ejemplo \"1,2,3,4,5,6,7\"";
                lblError.setText(mensajes);
            }
            if (elementos.length > 7) {
                valida = false;
                mensajes = "Debe ingresar un conjunto n elementos donde n<=7.\n "
                        + "Ejemplo \"1,2,3,4,5,6,7\"";
                lblError.setText(mensajes);
            }
        }
        return valida;
    }

    private void btnMostrarRelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRelacionesActionPerformed
        // TODO add your handling code here:
        Thread hilo;
        Runnable miRunnable;
        miRunnable = new Runnable() {
            @Override
            public void run() {
                String relacionTransitiva = "";
                pgsProgreso.setValue(0);
                try {
                    for (String relacion : relaciones) {
                        relacionTransitiva += relacion + "\n";
                        txtaRelacionesTransitivas.setText(relacionTransitiva);
                        pgsProgreso.setValue(++porcentaje);
                        lblPorcentaje.setText(df.format(pgsProgreso.getPercentComplete() * 100) + " %");
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        };
        hilo = new Thread(miRunnable);
        hilo.start();
    }//GEN-LAST:event_btnMostrarRelacionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private boolean validador() {
        if (txtConjunto.getText().equals("")
                || txtConjunto.getForeground() == color) {
            mensajes = "Debe ingresar un conjunto de elementos separados por coma.\n "
                    + "Ejemplo \"1,2,3,4,5,6,7\"";
            lblError.setText(mensajes);
            return false;
        }
        mensajes = "";
        lblError.setText(mensajes);
        return true;
    }

    private String generarProductoCartesiano(String conjunto[]) {
        String pares = "";
        for (int i = 0; i < conjunto.length; i++) {
            for (int j = 0; j < conjunto.length; j++) {
                pares += "(" + conjunto[i] + "," + conjunto[j] + ")";
                if (i + 1 != conjunto.length || j + 1 < conjunto.length) {
                    pares += ", ";
                }
            }
        }
        return pares;
    }

    public static boolean esTransitiva(String parAB, String parBC, String parAC) {
        boolean esTransitiva = false;
        String paresAB[] = parAB.split(",");
        String paresBC[] = parBC.split(",");
        String paresAC[] = parAC.split(",");
        if (paresAB[0].equalsIgnoreCase(paresAC[0])
                && paresBC[1].equalsIgnoreCase(paresAC[1])) {
            esTransitiva = true;
        }
        return esTransitiva;
    }

    public static ArrayList obtenerTransitivas(String relacion[]) {
        String parAB = "", parBC = "", parAC = "";
        ArrayList transitivas = new ArrayList();
        for (int i = 0; i < relacion.length; i++) {
            parAB = relacion[i];
            for (int j = 0; j < relacion.length; j++) {
                parBC = relacion[j];
                for (int k = 0; k < relacion.length; k++) {
                    parAC = relacion[k];
                    if (esTransitiva(parAB, parBC, parAC)) {
                        transitivas.add(parAB + " - " + parBC + " - " + parAC);
                    }
                }
            }
        }
        return transitivas;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularRelaciones;
    private javax.swing.JButton btnMostrarRelaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConjunto;
    private javax.swing.JLabel lblConjuntosDistintos;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblProductoCartesiano;
    private javax.swing.JLabel lblRelaciones;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTransitivas;
    private javax.swing.JProgressBar pgsProgreso;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JTextField txtConjunto;
    private javax.swing.JTextField txtRelaciones;
    private javax.swing.JTextField txtSubconjuntos;
    private javax.swing.JTextArea txtaProductoCartesiano;
    private javax.swing.JTextArea txtaRelacionesTransitivas;
    // End of variables declaration//GEN-END:variables
}
