/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalmatedisc;

import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author alfredo
 */
public class Problema1 extends javax.swing.JDialog {

    private Color color;
    private int porcentaje = 0;
    private String mensajes;
    DecimalFormat df = new DecimalFormat("0.00"); 
    
    /**
     * Creates new form Problema1
     */
    public Problema1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        color = txtConjunto.getForeground();
        txtConjunto.setDocument(new LimitadorCaracteres(txtConjunto, 7));
        txtConjunto.setText("1,2,3,4");
        txtConjunto.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblConjunto = new javax.swing.JLabel();
        txtConjunto = new javax.swing.JTextField();
        lblRelaciones = new javax.swing.JLabel();
        txtRelaciones = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaSubconjuntos = new javax.swing.JTextArea();
        lblConjuntosDistintos = new javax.swing.JLabel();
        btnCalcularRelaciones = new javax.swing.JButton();
        pgsProgreso = new javax.swing.JProgressBar();
        lblProductoCartesiano = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaProductoCartesiano = new javax.swing.JTextArea();
        lblSubconjuntos = new javax.swing.JLabel();
        txtSubconjuntos = new javax.swing.JTextField();
        btnGenerarRelaciones = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblPorcentaje = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Problema 1");
        setModal(true);

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitulo.setText("PROYECTO FINAL - PROBLEMA 1");

        lblConjunto.setText("Introduce los elementos del conjunto: ");

        txtConjunto.setForeground(new java.awt.Color(204, 204, 255));
        txtConjunto.setText("1,2,3,4");
        txtConjunto.setToolTipText("Separa con comas los elementos del conjunto");
        txtConjunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConjuntoMouseClicked(evt);
            }
        });
        txtConjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConjuntoActionPerformed(evt);
            }
        });
        txtConjunto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConjuntoFocusLost(evt);
            }
        });
        txtConjunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConjuntoKeyTyped(evt);
            }
        });

        lblRelaciones.setText("Total de relaciones:");

        txtRelaciones.setEnabled(false);

        txtaSubconjuntos.setColumns(20);
        txtaSubconjuntos.setRows(5);
        txtaSubconjuntos.setEnabled(false);
        jScrollPane1.setViewportView(txtaSubconjuntos);

        lblConjuntosDistintos.setText("Conjuntos Distintos:");

        btnCalcularRelaciones.setText("Calcular Relaciones");
        btnCalcularRelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRelacionesActionPerformed(evt);
            }
        });

        lblProductoCartesiano.setText("Producto Cartesiano:");

        txtaProductoCartesiano.setColumns(20);
        txtaProductoCartesiano.setRows(5);
        txtaProductoCartesiano.setEnabled(false);
        jScrollPane2.setViewportView(txtaProductoCartesiano);

        lblSubconjuntos.setText("Total de Subconjuntos:");

        txtSubconjuntos.setEnabled(false);

        btnGenerarRelaciones.setText("Generar Relaciones");
        btnGenerarRelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRelacionesActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(204, 0, 0));

        lblPorcentaje.setText("0.00 %");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlContenedorLayout = new org.jdesktop.layout.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlContenedorLayout.createSequentialGroup()
                .add(42, 42, 42)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlContenedorLayout.createSequentialGroup()
                        .add(lblError)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(pnlContenedorLayout.createSequentialGroup()
                        .add(lblConjuntosDistintos)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlContenedorLayout.createSequentialGroup()
                        .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(pnlContenedorLayout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(btnSalir)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(lblPorcentaje))
                            .add(pgsProgreso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jScrollPane1)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, pnlContenedorLayout.createSequentialGroup()
                                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(lblConjunto)
                                    .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(lblProductoCartesiano)
                                        .add(lblRelaciones))
                                    .add(lblSubconjuntos))
                                .add(37, 37, 37)
                                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(pnlContenedorLayout.createSequentialGroup()
                                        .add(txtConjunto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(btnCalcularRelaciones))
                                    .add(jScrollPane2)
                                    .add(pnlContenedorLayout.createSequentialGroup()
                                        .add(txtRelaciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(pnlContenedorLayout.createSequentialGroup()
                                        .add(txtSubconjuntos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 198, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(btnGenerarRelaciones))))
                            .add(pnlContenedorLayout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(lblTitulo)
                                .add(172, 172, 172)))
                        .add(88, 88, 88))))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlContenedorLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(lblTitulo)
                .add(26, 26, 26)
                .add(lblError)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblConjunto)
                    .add(txtConjunto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnCalcularRelaciones))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblRelaciones)
                    .add(txtRelaciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblProductoCartesiano)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblSubconjuntos)
                    .add(txtSubconjuntos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnGenerarRelaciones))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lblConjuntosDistintos)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pgsProgreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(pnlContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblPorcentaje)
                    .add(btnSalir))
                .add(19, 19, 19))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(81, 81, 81)
                .add(pnlContenedor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 773, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlContenedor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConjuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConjuntoMouseClicked
        // TODO add your handling code here:
        if (txtConjunto.getForeground() == color) {
            txtConjunto.setText("");
            txtConjunto.setForeground(txtRelaciones.getForeground());
        }
    }//GEN-LAST:event_txtConjuntoMouseClicked

    private void txtConjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConjuntoActionPerformed
        // TODO add your handling code here:
        btnCalcularRelacionesActionPerformed(evt);
    }//GEN-LAST:event_txtConjuntoActionPerformed

    private void txtConjuntoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConjuntoFocusLost
        // TODO add your handling code here:
        if (txtConjunto.getText().equalsIgnoreCase("")) {
            txtConjunto.setForeground(color);
            txtConjunto.setText("1,2,3,4");
            txtRelaciones.setText("");
            txtaProductoCartesiano.setText("");
            txtSubconjuntos.setText("");
            txtaSubconjuntos.setText("");
            lblError.setText("");
            pgsProgreso.setValue(0);
        }
    }//GEN-LAST:event_txtConjuntoFocusLost

    private void txtConjuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConjuntoKeyTyped
        // TODO add your handling code here:
        if (txtConjunto.getForeground() == color) {
            txtConjunto.setText("");
            txtConjunto.setForeground(txtRelaciones.getForeground());
        }
    }//GEN-LAST:event_txtConjuntoKeyTyped

    private void btnCalcularRelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRelacionesActionPerformed
        // TODO add your handling code here:
        if (!validador()) {
            return;
        }
        int relaciones;
        String pares;
        porcentaje = 0;
        txtaSubconjuntos.setText("");
        lblPorcentaje.setText("0.00 %");
        pgsProgreso.setValue(0);
        
        relaciones = (int) Math.pow(2, txtConjunto.getText().split(",").length);
        pgsProgreso.setMaximum((int) Math.pow(2, relaciones));
        txtRelaciones.setText("" + relaciones);
        pares = generarProductoCartesiano(txtConjunto.getText().split(","));
        txtaProductoCartesiano.setText(pares);
        txtSubconjuntos.setText("" + pgsProgreso.getMaximum());
    }//GEN-LAST:event_btnCalcularRelacionesActionPerformed

    private String generarProductoCartesiano(String conjunto[]) {
        String pares = "";
        for (int i = 0; i < conjunto.length; i++) {
            for (int j = 0; j < conjunto.length; j++) {
                pares += "(" + conjunto[i] + "," + conjunto[j] + ")";
                if (i + 1 != conjunto.length || j + 1 < conjunto.length) {
                    pares += ", ";
                }
            }
        }
        return pares;
    }
    
    private void btnGenerarRelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRelacionesActionPerformed
        // TODO add your handling code here:
        Thread hilo;
        Runnable miRunnable = new Runnable() {
            public void run() {
                pgsProgreso.setValue(0);
                try {
                    String pares = generarProductoCartesiano(txtConjunto.getText().split(","));
                    String subs = generarRelacionesDistintasRecursivo(pares.split(", "));
                    txtaSubconjuntos.setText(subs);
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        };
        hilo = new Thread(miRunnable);
        hilo.start();
    }//GEN-LAST:event_btnGenerarRelacionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private String generarRelacionesDistintasRecursivo(String pares[]) {
        String combinacion = "";
        String subconjunto = "";
        String aux = "";
        porcentaje = 1;
        for (int i = 0; i < pares.length; i++) {
            combinacion = ciclo(aux, subconjunto, combinacion, pares, i, pares.length);
        }
        return combinacion;
    }

    private String ciclo(String aux, String subconjunto, String combinacion, String pares[], int i, int ciclos) {
        if (i >= pares.length) {
            return combinacion;
        }
        aux = subconjunto;
        subconjunto = subconjunto + pares[i];
        combinacion += "{" + subconjunto + "}" + ", \n";
        txtaSubconjuntos.setText(combinacion);
        pgsProgreso.setValue(++porcentaje);  
        lblPorcentaje.setText(df.format(pgsProgreso.getPercentComplete() * 100) + " %");
        for (int j = 1; ciclos >= 0; j++) {
            combinacion = ciclo(aux, subconjunto, combinacion, pares, i + j, --ciclos);
        }
        subconjunto = aux;
        return combinacion;
    }
    
    private boolean validador() {
        if (txtConjunto.getText().equals("")
                || txtConjunto.getForeground() == color) {
            mensajes = "Debe ingresar un conjunto de elementos separados por coma.\n "
                    + "Ejemplo \"1,2,3,4\"";
            lblError.setText(mensajes);
            return false;
        }
        mensajes = "";
        lblError.setText(mensajes);
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularRelaciones;
    private javax.swing.JButton btnGenerarRelaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConjunto;
    private javax.swing.JLabel lblConjuntosDistintos;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblProductoCartesiano;
    private javax.swing.JLabel lblRelaciones;
    private javax.swing.JLabel lblSubconjuntos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JProgressBar pgsProgreso;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JTextField txtConjunto;
    private javax.swing.JTextField txtRelaciones;
    private javax.swing.JTextField txtSubconjuntos;
    private javax.swing.JTextArea txtaProductoCartesiano;
    private javax.swing.JTextArea txtaSubconjuntos;
    // End of variables declaration//GEN-END:variables
}
